[project]
name = "vpm"
version = "0.01"
dependencies = [
    "typer",
    "sqlmodel",
    "pycountry",
    "python-dateutil",
]

[project.scripts]
vpm = "vpm.cli:app"

[tool.setuptools]
packages = ["vpm"]

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"