[project]
name = "vpm"
version = "0.01"
dependencies = [
    "typer",
    "sqlmodel",
    "pycountry",
    "python-dateutil",
    ]

[tool.setuptools]
package-dir = {"" = "src"}

[project.scripts]
vpm = "vpm.cli:app"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"